- postgresql_db: name={{ dbname }} state=present login_user={{ dbadmin }} login_password={{ dbadminpw }} login_host={{ dbhost }}
  register: rds_db

- postgresql_ext: db={{ dbname }} name={{ item }} login_user={{ dbadmin }} login_password={{ dbadminpw }} login_host={{ dbhost }}
  with_items:
      - postgis
      - postgis_topology

- postgresql_user: name={{ dbuser }} password={{ dbpass }} db={{ dbname }} priv=ALL login_user={{ dbadmin }} login_password={{ dbadminpw }} login_host={{ dbhost }}
  when: rds_db.changed
