- block:
    - yum: name=python27-psycopg2 state=present
      become: yes
      tags:
        - deps

    - file:
        path: /var/log/hope
        state: directory
        mode: 0755
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
      become: yes
      tags:
        - config
  rescue:
    - include: rescue.yml state=common
