---
- hosts: frontend
  remote_user: ec2-user
  pre_tasks:
      - local_action: include pre.yml
        run_once: true
  roles:
      - common
      - { role: hopestarterdb, dbhost: "{{ rds.instance.endpoint }}" }
      - { role: hopeapi, dbhost: "{{ rds.instance.endpoint }}"  }
      - { role: hopeweb, dbhost: "{{ rds.instance.endpoint }}"  }
      - { role: hopesecrets }
  post_tasks:
      - include: post.yml
  vars:
      rds_instance_name: HopestarterTest
      dbuser: "{{ lookup('env','PGUSER') }}"
      dbpass: "{{ lookup('env','PGPASS') }}"
      dbadmin: postgres
      dbadminpw: postgres
      become_user: root
      become_method: sudo
      repo_url: "https://github.com/hopestarter/hopestarterapp.git"
      app_home: /home/ec2-user/
      app_settings: hopestarter.settings.api_production
