---
- hosts: frontend
  remote_user: ec2-user
  pre_tasks:
    - block:
        - local_action:
            module: slack
            token: "{{ slack_token }}"
            msg: "Starting deployment"
          when: slack_token is defined
          tags:
            - db
            - code
            - config
        - local_action:
            module: rds
            command: facts
            instance_name: "{{ rds_instance_name }}"
          register: rds
          tags:
            - db
            - code
            - config
      rescue:
        - include: rescue.yml state=pre_tasks
  roles:
      - common
      - { role: hopestarterdb, dbhost: "{{ rds.instance.endpoint }}" }
      - { role: hopeapi, dbhost: "{{ rds.instance.endpoint }}"  }
      - { role: hopeweb, dbhost: "{{ rds.instance.endpoint }}"  }
      - { role: hopesecrets }
  post_tasks:
    - local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Deployment finished."
      when: slack_token is defined
      tags:
        - db
        - code
        - config
  vars:
      rds_instance_name: HopestarterTest
      dbuser: "{{ lookup('env','PGUSER') }}"
      dbpass: "{{ lookup('env','PGPASS') }}"
      dbadmin: postgres
      dbadminpw: postgres
      become_user: root
      become_method: sudo
      repo_url: "https://github.com/hopestarter/hopestarterapp.git"
      app_home: /home/ec2-user/
      app_settings: hopestarter.settings.api_production
