- yum: name={{ item }} state=present enablerepo=epel
  become: yes
  with_items:
      - git
      - postgresql94-devel
      - gcc
      - geos
      - gdal
      - nginx

- git: repo={{ repo_url }} dest="{{ app_home }}/hopestarterapp"

- pip: name=virtualenv state=present extra_args="--user"

- pip: requirements="{{ app_home }}/hopestarterapp/requirements/production.txt" virtualenv="{{ app_home }}/venv" virtualenv_site_packages=yes
