- name: installing system level dependencies
  yum: name={{ item }} state=present enablerepo=epel
  become: yes
  with_items:
      - git
      - postgresql94-devel
      - gcc
      - geos
      - gdal
      - nginx

- name: updating source code to {{ git_version }}
  git: repo={{ repo_url }} dest="{{ app_home }}/hopestarterapp" version={{ git_version }}

- name: installing virtualenv
  pip: name=virtualenv state=present extra_args="--user"

- name: installing python dependencies
  pip: requirements="{{ app_home }}/hopestarterapp/requirements/production.txt" virtualenv="{{ app_home }}/venv" virtualenv_site_packages=yes
