- include: migrate.yml
  when: migrate_django == "true"
  tags:
      - db

- name: running collectstatic
  django_manage: command=collectstatic app_path="{{ django_home }}" virtualenv="{{ venv_path }}" settings="{{ app_settings }}"
  environment: "{{djangoenv}}"
  tags:
      - code
